---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: vault-issuer
    cert-manager.io/common-name: {{ .Values.name }}.k8s-app.fredcorp.com
  name: {{ .Values.name }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.name }}.k8s-app.fredcorp.com
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.name }}
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.name }}.k8s-app.fredcorp.com
    secretName: {{ .Values.name }}