---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: e2e-tests-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: e2e-tests
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "GET"
          - "https://{{ .Values.name }}.{{ .Release.Namespace}}.svc.cluster.local:8080"
      restartPolicy: Never
  backoffLimit: 2