---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
  - protocol: TCP
    port: 808
    targetPort: 8080
    name: http