---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: e2e-tests-
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: e2e-tests
        image: alpine
        command:
          - "/bin/sh"
          - "-c"
          - |
            apk add curl
            response_code=$(curl -fsSkLw "%{http_code}" "http://{{ .Values.name }}.{{ .Release.Namespace}}.svc.cluster.local:8080" -o /dev/null)
            echo "Response code is $response_code"
            if [ $response_code -eq 200 ]; then
              echo "SUCCESS : response code is $response_code"
              exit 0
            else
              echo "FAIL : response code is $response_code"
              exit 1
            fi
      restartPolicy: Never
  backoffLimit: 0