---
name: Release docker image
on:
  workflow_dispatch:
    inputs:
      release-type:
        required: true
        type: choice
        options:
          - "GA"
          - "RC"
        default: "GA"
        description: General Availability or Release Candidate
jobs:
  release:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/docker-release-app.yaml@main
    with:
      workingdir: app
      img-name: demo-web
      cache-registry: docker.io/ixxel
      registry-url: docker.io
      registry-username: ${{ vars.DOCKER_HUB_USER }}
      prerelease: "${{ inputs.release-type == 'RC' }}"
    secrets:
      git-token: ${{ secrets.PAT }}
      registry-password: ${{ secrets.DOCKER_IO_PWD }}
